---
- name: "set {{ mailserver_domain }} as hostname"
  become: true
  ansible.builtin.hostname:
    name: "{{ mailserver_domain }}"

- name: Add hostname to /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ inventory_hostname }} {{ ansible_hostname }} {{ additional_dns_maildomains }}"
    state: present

- name: Set /etc/mailname
  become: true
  ansible.builtin.copy:
    dest: "/etc/mailname"
    content: "{{ mailserver_domain }}"
    mode: '0644'

- name: set own dns resolver
  become: true
  ansible.builtin.template:
    src: templates/resolve.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
