---
- name: perform optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: configure local hostnames
  ansible.builtin.include_tasks: hosts.yml

- name: configure vmail user
  ansible.builtin.include_tasks: user.yml

- name: configure mariadb
  ansible.builtin.include_tasks: mariadb.yml
