---
- name: create mail group
  group:
    name: "{{ mailserver__group }}"
    state: present

- name: Create mail user
  become: true
  user:
    name: "{{ mailserver__user }}"
    home: "{{ mailserver__home }}"
    group: "{{ mailserver__group }}"
    shell: "{{ mailserver__shell }}"

- name: Create mail user sieve directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: vmail
    group: vmail
    mode: 0750
  with_items:
    - "{{ mailserver__home }}"
    - "{{ mailserver__home }}/sieve"
    - "{{ mailserver__home }}/sieve/global"

- name: Create mail user mailbox directory
  become: true
  file:
    path: /var/vmail/mailboxes
    state: directory
    owner: vmail
    group: vmail
    mode: '0770'
